name: Build & Push binaries

permissions:
  contents: write

on:
  pull_request:
  push:
      paths-ignore:
        - '.gitignore'
        - 'LICENSE'
        - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { runner: windows-latest, os: windows, arch: x64    }
        - { runner: ubuntu-latest,  os: linux,   arch: x86_64 }
        - { runner: macos-latest,   os: macos,   arch: x86_64 }
        mode: [debug, releasedbg]

    runs-on: ${{ matrix.platform.runner }}

    steps:
    - name: Get current date as package key
      id: cache_key
      run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Set OUTPUT_FOLDER variable"
      run: echo "OUTPUT_FOLDER=${{ matrix.platform.os }}_${{ matrix.platform.arch }}_${{ matrix.mode }}" >> $GITHUB_ENV
      shell: bash

    # Force xmake to a specific folder (for cache)
    - name: Set xmake env
      run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v3

    # Install xmake
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

    # Update xmake repository (in order to have the file that will be cached)
    - name: Update xmake repository
      run: xmake repo --update

    # Fetch xmake dephash
    - name: Retrieve dependencies hash
      id: dep_hash
      run: echo "hash=$(xmake l utils.ci.packageskey)" >> $GITHUB_OUTPUT
      shell: bash

    # Cache xmake dependencies
    - name: Retrieve cached xmake dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
        key: ${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ matrix.mode }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}

    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.platform.arch }} --mode=${{ matrix.mode }} --yes

    - name: Build
      run: xmake

    - name: Install
      run: |
        mkdir dest/
        xmake install -vo dest/
        if [ "$RUNNER_OS" == "Linux" ]; then
          mv ./dest/lib/*.so ./dest/bin/
        elif [ "$RUNNER_OS" == "macOS" ]; then
          mv ./dest/lib/*.dylib ./dest/bin/
        fi
        rm -rf dest/include/
        rm -rf dest/lib/
      shell: bash

    - uses: vimtor/action-zip@v1
      with:
        files: dest/
        dest: ${{ env.OUTPUT_FOLDER }}.zip

    # Nightly tags (for commits to dev branch)
    - name: Upload binaries to release (Branch)
      uses: svenstaro/upload-release-action@v2
      if: ${{ (github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.OUTPUT_FOLDER }}.zip
        asset_name: ${{ env.OUTPUT_FOLDER }}.zip
        tag: "0.0.0-nightly"
        overwrite: true
        body: "Dev branch"

    # Release tags (for tags)
    - name: Upload binaries to release (Tag)
      uses: svenstaro/upload-release-action@v2
      if: ${{ startsWith(github.event.ref, 'refs/tags/') && matrix.mode == 'releasedbg' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.OUTPUT_FOLDER }}.zip
        asset_name: ${{ env.OUTPUT_FOLDER }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: Version ${{ github.ref }}
